[project]
authors = ["ThanosSkentzos <kalligerist@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "SNA-14B"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
graph-tool = ">=2.80,<3"
jupyter = ">=1.1.1,<2"
networkx = ">=3.4.2,<4"
